CREATE TABLE
  bible_versions (
    name TEXT PRIMARY KEY,
    title TEXT not null,
    OT BOOLEAN,
    NT BOOLEAN
  );
/*CREATE TABLE
  commentary_versions (
    name TEXT PRIMARY KEY,
    title TEXT unique,
    author TEXT
  );
CREATE TABLE
  dictionary_versions (
    name TEXT PRIMARY KEY,
    title TEXT unique,
    author TEXT
  );
CREATE TABLE
  concordance_versions (
    name TEXT PRIMARY KEY,
    title TEXT unique,
    author TEXT
  );*/

CREATE TABLE
  bible_books (
    id SMALLINT PRIMARY KEY, 
    name TEXT not null unique,
    title TEXT,
    code TEXT unique,
    chapters smallint not null
  );

CREATE TABLE
  kjv_headings (
    id SMALLINT PRIMARY KEY,
    bk_id SMALLINT not null,
    chapter SMALLINT not null,
    data jsonb
  );

CREATE TABLE
  bible_references (
    id SMALLINT PRIMARY KEY,
    bk_id TEXT not null,
    chapter smallint not null,
    verse smallint not null,
    ref TEXT not null unique
  );

CREATE TABLE
  bible_verses (
    id BIGINT generated by default as identity PRIMARY KEY,
    ref_id SMALLINT not null,
    version_id TEXT not null,
    txt TEXT not null
  );

CREATE TABLE
  commentary (
    id BIGINT generated by default as identity PRIMARY KEY,
    ref_id SMALLINT not null,
    version_name TEXT not null,
    --txt TEXT not null,
    com TEXT
  );

CREATE TABLE
  concordance (
    id INTEGER generated by default as identity PRIMARY KEY,
    version_name TEXT not null,
    sn TEXT not null,
    wrd TEXT not null,
    data jsonb
  );

CREATE TABLE
  dictionary (
    id BIGINT generated by default as identity PRIMARY KEY,
    version_name TEXT not null,
    sn TEXT not null,
    wrd TEXT not null,
    data jsonb
  );
