create table
  public.countries (
    id bigint generated by default as identity not null,
    name text null,
    iso2 text not null,
    iso3 text null,
    local_name text null,
    continent public.continents null,
    constraint countries_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.accounts (
    id uuid not null default extensions.uuid_generate_v4 (),
    case_number bigint not null,
    reason text not null,
    rrr text null,
    invoice_no text not null,
    receipt_no text null,
    subject text not null,
    email text not null,
    amount bigint not null,
    currency text null default 'NGN'::text,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint accounts_pkey primary key (id),
    constraint accounts_case_number_fkey foreign key (case_number) references investigations (case_number)
  ) tablespace pg_default;

  create table
  public.applications (
    id uuid not null default extensions.uuid_generate_v4 (),
    title text null,
    type text null,
    reasons text[] null,
    methods text[] null,
    product_types text[] null,
    product_location text null,
    company_name text null,
    company_address text null,
    contact_name text null,
    email text null,
    phone text null,
    city text null,
    state text null,
    date date null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint applications_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.destructions (
    id uuid not null default extensions.uuid_generate_v4 (),
    type_of text not null,
    address text not null,
    reasons text[] not null,
    methods text[] not null,
    product_types text[] not null,
    date date not null,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint destructions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.files (
    id uuid not null default extensions.uuid_generate_v4 (),
    file_number bigint not null,
    subject text not null,
    volume smallint not null,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint files_pkey primary key (id),
    constraint files_file_number_key unique (file_number)
  ) tablespace pg_default;

  create table
  public.histories (
    id serial not null,
    doc_id uuid not null,
    collection_id text not null,
    table_name text not null,
    action text not null default ''::text,
    action_by uuid not null default auth.uid (),
    time timestamp with time zone not null default now(),
    constraint history_pkey primary key (id),
    constraint history_action_by_fkey foreign key (action_by) references auth.users (id)
  ) tablespace pg_default;

  create table
  public.investigations (
    id uuid not null default extensions.uuid_generate_v4 (),
    case_number bigint generated by default as identity not null,
    file_number bigint null,
    mail_id uuid null,
    complaint text not null,
    company text null,
    contact text null,
    phone text null,
    email text null,
    details text not null,
    unit uuid not null,
    ipo uuid not null,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint investigations_pkey primary key (id),
    constraint investigations_case_number_key unique (case_number),
    constraint investigations_mail_id_fkey foreign key (mail_id) references mails (id)
  ) tablespace pg_default;

  create table
  public.mails (
    id uuid not null default extensions.uuid_generate_v4 (),
    title text not null,
    file_number bigint not null,
    source text not null,
    in_date date not null,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint mails_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.minutes (
    id serial not null,
    doc_id uuid not null,
    collection_id text not null,
    comment text not null default ''::text,
    from_user uuid not null default auth.uid (),
    to_user uuid not null,
    time timestamp with time zone not null default now(),
    constraint minutes_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.profiles (
    id uuid not null,
    name text not null,
    email text not null,
    phone text null,
    title text null,
    level smallint not null default 0,
    role text not null default 'public'::text,
    staff_id text null,
    rank text null,
    unit uuid null,
    location text null,
    status text not null default 'active'::text,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    constraint profiles_pkey primary key (id),
    constraint profiles_created_by_fkey foreign key (created_by) references auth.users (id),
    constraint profiles_id_fkey foreign key (id) references auth.users (id),
    constraint profiles_unit_fkey foreign key (unit) references units (id)
  ) tablespace pg_default;

  create table
  public.raids (
    id uuid not null default extensions.uuid_generate_v4 (),
    case_number bigint null,
    type_of text not null,
    date date not null,
    offence text not null,
    address text not null,
    team text[] not null,
    ipos text[] null,
    mopols numeric null default 2,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint raids_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.samples (
    id uuid not null default extensions.uuid_generate_v4 (),
    case_number bigint not null,
    product text not null,
    man_name text null,
    man_address text null,
    man_country text null,
    man_date text null,
    expiry_date text null,
    category text not null,
    nafdac_no text null,
    batch text null,
    pack_size text null,
    quantity text not null,
    date_sent date not null,
    location text not null,
    status text not null default ''::text,
    submitted boolean not null default false,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    minuted_to uuid null,
    minuted_by uuid null,
    constraint samples_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.units (
    id uuid not null default extensions.uuid_generate_v4 (),
    created_at timestamp with time zone not null default now(),
    created_by uuid not null default auth.uid (),
    abbrev text null,
    name text null,
    location text null,
    status text null,
    constraint units_pkey primary key (id),
    constraint units_created_by_fkey foreign key (created_by) references auth.users (id)
  ) tablespace pg_default;

  /*create table
  public.users (
    id serial not null,
    "first_name" character varying(30) not null,
    "last_name" character varying(30) not null,
    email character varying(50) not null,
    password character varying(255) not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null,
    "deleted_at" timestamp with time zone null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email)
  ) tablespace pg_default;*/